[package]
name = "rust_d3_delaunay"
version = "0.1.0"
authors = ["martin frances <martinfrances107@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "~0.5"
delaunator = { git = "https://github.com/mourner/delaunator-rs.git" }
geo = "~0.23"
num-traits = "~0.2"
rust_d3_geo = { git = "https://github.com/martinfrances107/rust_d3_geo.git", branch = "main" }
derivative = "~2"
[dev-dependencies]
pretty_assertions = "~1"
