[workspace]
members = [
  "./lib",
  "examples/cross_pattern",
  "examples/n_points",
]

resolver = "2"
[workspace.package]
authors = ["martin frances <martinfrances107@hotmail.com>"]
edition = "2021"
license = "MIT"
version = "0.7.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
d3_geo_rs = "~2"
delaunator = "~1"
geo = "~0.26"
geo-types = "~0.7"
num-traits = "~0.2"
pretty_assertions = "~1"
generator = "0.7"
