[package]
authors = ["martin frances <martinfrances107@hotmail.com>"]
categories = ["graphics", "Mathematics"]
description = "A port of D3/d3-delauany"
edition = "2021"
license = "MIT"
keywords = ["delauany", "diagram", "graphics", "voronoi"]
name = "d3_delaunay_rs"
repository = "https://github.com/martinfrances107/rust_d3_delaunay"
version = "0.6.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
d3_geo_rs = "~2"
delaunator = "~1"
geo = "~0.26"
geo-types = "~0.7"
num-traits = "~0.2"

[dev-dependencies]
pretty_assertions = "~1"
