[package]
authors = ["martin frances <martinfrances107@hotmail.com>"]
categories = ["graphics"]
description = "A port of D3/d3-delauany"
edition = "2021"
license = "MIT"
keywords = ["graphics", "d3-delauany"]
name = "d3_delaunay_rs"
repository = "https://github.com/martinfrances107/rust_d3_delaunay"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "~0.5"
delaunator = "~1"
geo = "~0.23"
geo-types = "~0.7"
num-traits = "~0.2"
d3_geo_rs = "~0.1"
derivative = "~2"

[dev-dependencies]
pretty_assertions = "~1"
