[package]
authors = ["martin <martinfrances107@hotmail.com>"]
edition = "2021"
keywords = ["demo", "graphics"]
license = "MIT"
name = "cross_pattern"
readme = "README.md"
repository = "https://github.com/martinfrances107/rust_d3_geo"
version = "0.1.0"
# Version 1.65 is required as this package makes use of "Generic Associated Types".
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
d3_delaunay_rs = { path = "../../" }
geo = "~0.26"
svg = "~0.13"
geo-types = "~0.7"
rand = "~0.8"
